modLoader = "javafml"
loaderVersion = "[${loader_version},)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "generalfeedback"
version = "1.0.0"
displayName = "GeneralFeedback"
authors = "zhenshiz"
description = "Just submit feedbacks to authors of projects."
logoFile = "icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.generalfeedback]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.197,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generalfeedback]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "generalfeedback.mixins.json"
